// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VIRTUAL_CLASSE_FORMATION.Data;

#nullable disable

namespace VIRTUAL_CLASSE_FORMATION.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.Formateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarId")
                        .HasColumnType("longtext");

                    b.Property<string>("AvatarModel")
                        .HasColumnType("longtext");

                    b.Property<string>("Biographie")
                        .HasColumnType("longtext");

                    b.Property<string>("LlmId")
                        .HasColumnType("longtext");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PersonaId")
                        .HasColumnType("longtext");

                    b.Property<string>("SystemPrompt")
                        .HasColumnType("longtext");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.Property<string>("VoiceId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("Formateurs");
                });

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.Formation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FormateurId")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("FormateurId");

                    b.ToTable("Formations");
                });

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.Inscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApprenantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FormationId")
                        .HasColumnType("int");

                    b.Property<int>("Progression")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApprenantId");

                    b.HasIndex("FormationId");

                    b.ToTable("Inscriptions");
                });

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.Modalite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contenu")
                        .HasColumnType("longtext");

                    b.Property<int>("ModuleFormationId")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModuleFormationId");

                    b.ToTable("Modalites");
                });

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.ModuleFormation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("FormationId")
                        .HasColumnType("int");

                    b.Property<int>("Ordre")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FormationId");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Enonce")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ModaliteId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModaliteId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.ReponseOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EstCorrecte")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("ReponseOptions");
                });

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.SessionFormation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FormationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormationId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.Formateur", b =>
                {
                    b.HasOne("VIRTUAL_CLASSE_FORMATION.Models.Utilisateur", "Utilisateur")
                        .WithOne("Formateur")
                        .HasForeignKey("VIRTUAL_CLASSE_FORMATION.Models.Formateur", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.Formation", b =>
                {
                    b.HasOne("VIRTUAL_CLASSE_FORMATION.Models.Categorie", "Categorie")
                        .WithMany("Formations")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VIRTUAL_CLASSE_FORMATION.Models.Formateur", "Formateur")
                        .WithMany("Formations")
                        .HasForeignKey("FormateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("Formateur");
                });

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.Inscription", b =>
                {
                    b.HasOne("VIRTUAL_CLASSE_FORMATION.Models.Utilisateur", "Apprenant")
                        .WithMany("Inscriptions")
                        .HasForeignKey("ApprenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VIRTUAL_CLASSE_FORMATION.Models.Formation", "Formation")
                        .WithMany("Inscriptions")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Apprenant");

                    b.Navigation("Formation");
                });

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.Modalite", b =>
                {
                    b.HasOne("VIRTUAL_CLASSE_FORMATION.Models.ModuleFormation", "ModuleFormation")
                        .WithMany("Modalites")
                        .HasForeignKey("ModuleFormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuleFormation");
                });

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.ModuleFormation", b =>
                {
                    b.HasOne("VIRTUAL_CLASSE_FORMATION.Models.Formation", "Formation")
                        .WithMany("Modules")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formation");
                });

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.Question", b =>
                {
                    b.HasOne("VIRTUAL_CLASSE_FORMATION.Models.Modalite", "Modalite")
                        .WithMany("Questions")
                        .HasForeignKey("ModaliteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modalite");
                });

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.ReponseOption", b =>
                {
                    b.HasOne("VIRTUAL_CLASSE_FORMATION.Models.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.SessionFormation", b =>
                {
                    b.HasOne("VIRTUAL_CLASSE_FORMATION.Models.Formation", "Formation")
                        .WithMany("Sessions")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formation");
                });

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.Categorie", b =>
                {
                    b.Navigation("Formations");
                });

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.Formateur", b =>
                {
                    b.Navigation("Formations");
                });

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.Formation", b =>
                {
                    b.Navigation("Inscriptions");

                    b.Navigation("Modules");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.Modalite", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.ModuleFormation", b =>
                {
                    b.Navigation("Modalites");
                });

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("VIRTUAL_CLASSE_FORMATION.Models.Utilisateur", b =>
                {
                    b.Navigation("Formateur");

                    b.Navigation("Inscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
